ifeq ($(strip $(PRODUCT_NAME)), Tinker_Board_2)

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libmraa
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MULTILIB := 64
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES_64 := lib64/libmraa.so
LOCAL_MODULE_TARGET_ARCH:= arm64
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmraajava
LOCAL_CHECK_ELF_FILES := false
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MULTILIB := 64
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SHARED_LIBRARIES := libc libdl libm libmraa
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES_64 := lib64/libmraajava.so
LOCAL_MODULE_TARGET_ARCH:= arm64
include $(BUILD_PREBUILT)

endif


