LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libmraa
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_SRC_FILES := lib64/libmraa.so
LOCAL_MODULE_TARGET_ARCH:= arm64
LOCAL_MULTILIB := 64
include $(BUILD_PREBUILT)

